In [1]:
##import library

import pandas as pd

In [2]:
## import dataset

df = pd.read_excel("data/DeltekDataMay2025.xlsx")
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 16385 entries, 0 to 16384
Data columns (total 65 columns):
 #   Column                                       Non-Null Count  Dtype
---  ------                                       --------------  -----
 0   Date Signed / Action Date                    16385 non-null  datetime64[ns]
 1   FY                                           16385 non-null  int64
 2   Action Type                                  16385 non-null  object
 3   Contract Number                              16385 non-null  object
 4   Contract Name                                16385 non-null  object
 5   Contract Vehicle                             6640 non-null   object
 6   Reason For Mod                               16385 non-null  object
 7   Action Amt ($K)                              16385 non-null  float64
 8   Contract FY 2024 Spend ($K)                  2663 non-null   float64
 9   Contract Spend to Date ($K)                  12354 non-null  float64
 10  Contract Ceiling Value ($K)                  12354 non-null  float64
 11  Contract Award Date                          12354 non-null  datetime64[ns]
 12  Contract Start Date                          12354 non-null  datetime64[ns]
 13  Contract Last Date to Order                  6525 non-null   datetime64[ns]
 14  Contract Ultimate Expiration Date            5829 non-null   datetime64[ns]
 15  Ultimate Completion Date of Transaction      15513 non-null  datetime64[ns]
 16  Task Order Number                            9863 non-null   object
 17  Modification Number                          16385 non-null  object
 18  Task Order Award Date                        10003 non-null  datetime64[ns]
 19  Task Order Start Date                        10003 non-null  datetime64[ns]
 20  Task Order Ultimate Expiration Date          9684 non-null   datetime64[ns]
 21  Task Order FY 2024 Spending ($K)             3451 non-null   float64
 22  Task Order Spending to Date ($K)             10003 non-null  float64
 23  Task Order Ceiling Value ($K)                9987 non-null   float64
 24  Task Order Percent of Ceiling Value Spent    5326 non-null   float64
 25  Funding Department                           16385 non-null  object
 26  Funding Agency                               15395 non-null  object
 27  Funding Division                             6554 non-null   object
 28  Funding Office                               2020 non-null   object
 29  Contracting Department                       16385 non-null  object
 30  Contracting Agency                           15648 non-null  object
 31  Contracting Division                         7056 non-null   object
 32  Contracting Office                           2280 non-null   object
 33  Category                                     16385 non-null  object
 34  Product or Service                           16385 non-null  object
 35  PSC-Description                              16385 non-null  object
 36  NAICS-Description                            16385 non-null  object
 37  Vendor                                       16385 non-null  object
 38  UEI                                          16385 non-null  object
 39  Contract Requirement Description             16384 non-null  object
 40  Requirement Category                         7598 non-null   object
 41  CO Business Size Determination               16385 non-null  object
 42  Small Disadvantaged Business                 16385 non-null  object
 43  Self Certified Small Disadvantaged Business  16385 non-null  object
 44  8(a)                                         16385 non-null  object
 45  SBA Certified 8(a) JV                        16385 non-null  object
 46  Veteran Owned                                16385 non-null  object
 47  Service-Disabled Veteran Owned               16385 non-null  object
 48  HUBZone                                      16385 non-null  object
 49  Self Certified HUBZone JV                    16385 non-null  object
 50  Woman Owned                                  16385 non-null  object
 51  Woman Owned Small Business                   16385 non-null  object
 52  EDWOSB                                       16385 non-null  object
 53  WOSB JV                                      16385 non-null  object
 54  EDWOSB JV                                    16385 non-null  object
 55  Alaska Native Corporation Owned              16385 non-null  object
 56  AbilityOne                                   16385 non-null  object
 57  Contract Type                                16385 non-null  object
 58  Set-Aside                                    16385 non-null  object
 59  Extent Competed                              16385 non-null  object
 60  Solicitation Procedure                       16385 non-null  object
 61  Place of Performance City                    15022 non-null  object
 62  Place of Performance State                   15022 non-null  object
 63  Place of Performance Country                 16385 non-null  object
 64  Place of Performance Country Code            15513 non-null  object
dtypes: datetime64[ns](9), float64(8), int64(1), object(47)
memory usage: 8.1+ MB

In [3]:
## remove columns not needed for analysis 

df1 = df.drop(df.columns[[1,2,3,8,9,10,12, 13, 16, 17,18,19,20,21,22,23,24,25,26,27,28,31,32,34,35,38,40,64]], axis=1)
df1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 16385 entries, 0 to 16384
Data columns (total 37 columns):
 #   Column                                       Non-Null Count  Dtype
---  ------                                       --------------  -----
 0   Date Signed / Action Date                    16385 non-null  datetime64[ns]
 1   Contract Name                                16385 non-null  object
 2   Contract Vehicle                             6640 non-null   object
 3   Reason For Mod                               16385 non-null  object
 4   Action Amt ($K)                              16385 non-null  float64
 5   Contract Award Date                          12354 non-null  datetime64[ns]
 6   Contract Ultimate Expiration Date            5829 non-null   datetime64[ns]
 7   Ultimate Completion Date of Transaction      15513 non-null  datetime64[ns]
 8   Contracting Department                       16385 non-null  object
 9   Contracting Agency                           15648 non-null  object
 10  Category                                     16385 non-null  object
 11  NAICS-Description                            16385 non-null  object
 12  Vendor                                       16385 non-null  object
 13  Contract Requirement Description             16384 non-null  object
 14  CO Business Size Determination               16385 non-null  object
 15  Small Disadvantaged Business                 16385 non-null  object
 16  Self Certified Small Disadvantaged Business  16385 non-null  object
 17  8(a)                                         16385 non-null  object
 18  SBA Certified 8(a) JV                        16385 non-null  object
 19  Veteran Owned                                16385 non-null  object
 20  Service-Disabled Veteran Owned               16385 non-null  object
 21  HUBZone                                      16385 non-null  object
 22  Self Certified HUBZone JV                    16385 non-null  object
 23  Woman Owned                                  16385 non-null  object
 24  Woman Owned Small Business                   16385 non-null  object
 25  EDWOSB                                       16385 non-null  object
 26  WOSB JV                                      16385 non-null  object
 27  EDWOSB JV                                    16385 non-null  object
 28  Alaska Native Corporation Owned              16385 non-null  object
 29  AbilityOne                                   16385 non-null  object
 30  Contract Type                                16385 non-null  object
 31  Set-Aside                                    16385 non-null  object
 32  Extent Competed                              16385 non-null  object
 33  Solicitation Procedure                       16385 non-null  object
 34  Place of Performance City                    15022 non-null  object
 35  Place of Performance State                   15022 non-null  object
 36  Place of Performance Country                 16385 non-null  object
dtypes: datetime64[ns](4), float64(1), object(32)
memory usage: 4.6+ MB

In [113]:
## format as categories and string

df1[["Solicitation Procedure","CO Business Size Determination","Small Disadvantaged Business", "Self Certified Small Disadvantaged Business","HUBZone"]]=df[["Solicitation Procedure","CO Business Size Determination","Small Disadvantaged Business", "Self Certified Small Disadvantaged Business","HUBZone"]].astype("category")
df1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 16385 entries, 0 to 16384
Data columns (total 38 columns):
 #   Column                                       Non-Null Count  Dtype
---  ------                                       --------------  -----
 0   Date Signed / Action Date                    16385 non-null  datetime64[ns]
 1   Contract Name                                16385 non-null  object
 2   Contract Vehicle                             6640 non-null   object
 3   Reason For Mod                               16385 non-null  object
 4   Action Amt ($K)                              16385 non-null  float64
 5   Contract Award Date                          12354 non-null  datetime64[ns]
 6   Contract Ultimate Expiration Date            5829 non-null   datetime64[ns]
 7   Ultimate Completion Date of Transaction      15513 non-null  datetime64[ns]
 8   Contracting Department                       16385 non-null  object
 9   Contracting Agency                           15648 non-null  object
 10  Category                                     16385 non-null  object
 11  NAICS-Description                            16385 non-null  object
 12  Vendor                                       16385 non-null  object
 13  Contract Requirement Description             16385 non-null  object
 14  CO Business Size Determination               16385 non-null  category
 15  Small Disadvantaged Business                 16385 non-null  category
 16  Self Certified Small Disadvantaged Business  16385 non-null  category
 17  8(a)                                         16385 non-null  object
 18  SBA Certified 8(a) JV                        16385 non-null  object
 19  Veteran Owned                                16385 non-null  object
 20  Service-Disabled Veteran Owned               16385 non-null  object
 21  HUBZone                                      16385 non-null  category
 22  Self Certified HUBZone JV                    16385 non-null  object
 23  Woman Owned                                  16385 non-null  object
 24  Woman Owned Small Business                   16385 non-null  object
 25  EDWOSB                                       16385 non-null  object
 26  WOSB JV                                      16385 non-null  object
 27  EDWOSB JV                                    16385 non-null  object
 28  Alaska Native Corporation Owned              16385 non-null  object
 29  AbilityOne                                   16385 non-null  object
 30  Contract Type                                16385 non-null  object
 31  Set-Aside                                    16385 non-null  object
 32  Extent Competed                              16385 non-null  object
 33  Solicitation Procedure                       16385 non-null  category
 34  Place of Performance City                    15022 non-null  object
 35  Place of Performance State                   15022 non-null  object
 36  Place of Performance Country                 16385 non-null  object
 37  EOI termination                              16385 non-null  boolean
dtypes: boolean(1), category(5), datetime64[ns](4), float64(1), object(27)
memory usage: 4.1+ MB

In [115]:
## How many are EOI related terminations? 

## format column as string, filter for "EOI" related contract terminations 

df1['Contract Requirement Description'] = df1['Contract Requirement Description'].astype("string")
df1['EOI termination'] = df1['Contract Requirement Description'].str.contains("EOI", case=False, na=False)
df1.head()

,Date Signed / Action Date,Contract Name,Contract Vehicle,Reason For Mod,Action Amt ($K),Contract Award Date,Contract Ultimate Expiration Date,Ultimate Completion Date of Transaction,Contracting Department,Contracting Agency,...,Alaska Native Corporation Owned,AbilityOne,Contract Type,Set-Aside,Extent Competed,Solicitation Procedure,Place of Performance City,Place of Performance State,Place of Performance Country,EOI termination
0,2025-05-01,(R) MINNESOTA UNIV:1107499 [24-008731]: IMMUNO...,NaN,Terminate for Convenience (complete or partial),0.0,2024-09-17,2025-05-01,2025-05-01,HEALTH AND HUMAN SERVICES,NATIONAL INSTITUTES OF HEALTH,...,N,N,Firm Fixed Price,No Set Aside Used,Not Competed,Single Source Solicited,Minneapolis,MN,United States,True
1,2025-05-01,HANDLS DXA BODY COMPOSITION AND BONE MINERAL D...,NaN,Terminate for Convenience (complete or partial),0.0,2023-08-16,2025-05-09,2025-05-09,HEALTH AND HUMAN SERVICES,NATIONAL INSTITUTES OF HEALTH,...,N,N,Firm Fixed Price,No Set Aside Used,Competed under SAP,Simplified Acquisition,Honolulu,HI,United States,True
2,2025-05-01,GSA CONSOLIDATED MULTIPLE AWARD SCHEDULE,GSA CONSOLIDATED MULTIPLE AWARD SCHEDULE,Terminate for Convenience (complete or partial),0.0,2008-07-31,NaT,2025-04-25,HEALTH AND HUMAN SERVICES,CENTERS FOR DISEASE CONTROL AND PREVENTION,...,N,N,Firm Fixed Price,Not Reported,Full and Open Competition,Multiple Awards Fair Opportunity,Atlanta,GA,United States,True
3,2025-05-01,GSA CONSOLIDATED MULTIPLE AWARD SCHEDULE,GSA CONSOLIDATED MULTIPLE AWARD SCHEDULE,Terminate for Convenience (complete or partial),0.0,NaT,NaT,2025-04-22,HEALTH AND HUMAN SERVICES,CENTERS FOR DISEASE CONTROL AND PREVENTION,...,N,N,Firm Fixed Price,Not Reported,Full and Open Competition,Multiple Awards Fair Opportunity,Gaithersburg,MD,United States,True
4,2025-05-01,SEWP V - SOLUTIONS FOR ENTERPRISEWIDE PROCUREM...,SEWP V - SOLUTIONS FOR ENTERPRISEWIDE PROCUREM...,Terminate for Convenience (complete or partial),0.0,2015-04-10,NaT,2025-05-01,AGRICULTURE,NaN,...,N,N,Firm Fixed Price,HUBZone Set-Aside,Full and Open Competition after exclusion of s...,Multiple Awards Fair Opportunity,Washington,DC,United States,False

In [45]:
## count number of contracts cancelled due to EOI compared to total contracts canceled 

df1['EOI termination'].value_counts()

EOI termination
False    15162
True      1223
Name: count, dtype: Int64

In [73]:
## EOI related terminations that were with small disadvantaged businesses

count = df1[(df1['EOI termination']) & (df1['Self Certified Small Disadvantaged Business'] == 'Y')].shape[0]
print(count)

372

In [75]:
## the ratio of EOI canceled contracts being with an SDB

EOI_SDB_count_ratio = 372/1223*100
print(round(EOI_SDB_ratio,2))

30.42

In [69]:
df1.groupby('EOI termination')['Action Amt ($K)'].sum().to_frame()

                 Action Amt ($K)
EOI termination
False                 -674899.44
True                   -16321.06

In [109]:
## create a df that only has EOI terminations 

df_EOI = df1[df1['EOI termination'] == True]
df_EOI.sample(10)

,Date Signed / Action Date,Contract Name,Contract Vehicle,Reason For Mod,Action Amt ($K),Contract Award Date,Contract Ultimate Expiration Date,Ultimate Completion Date of Transaction,Contracting Department,Contracting Agency,...,Alaska Native Corporation Owned,AbilityOne,Contract Type,Set-Aside,Extent Competed,Solicitation Procedure,Place of Performance City,Place of Performance State,Place of Performance Country,EOI termination
1135,2025-04-24,LONG TERM ADMINISTRATIVE SUPPORT CONTRACT III,NaN,Terminate for Convenience (complete or partial),0.0,2023-01-10,NaT,2026-11-28,HEALTH AND HUMAN SERVICES,NATIONAL INSTITUTES OF HEALTH,...,N,N,Firm Fixed Price,Not Reported,Full and Open Competition after exclusion of s...,Multiple Awards Fair Opportunity,Rockville,MD,United States,True
193,2025-04-30,GSA CONSOLIDATED MULTIPLE AWARD SCHEDULE,GSA CONSOLIDATED MULTIPLE AWARD SCHEDULE,Terminate for Convenience (complete or partial),0.0,2013-06-24,NaT,2027-08-31,HEALTH AND HUMAN SERVICES,CENTERS FOR MEDICARE AND MEDICAID SERVICES,...,N,N,Time and Materials,Not Reported,Full and Open Competition,Multiple Awards Fair Opportunity,Mclean,VA,United States,True
7949,2025-03-12,HCATS - HUMAN CAPITAL AND TRAINING SOLUTIONS,HCATS - HUMAN CAPITAL AND TRAINING SOLUTIONS,Terminate for Convenience (complete or partial),0.0,2016-05-11,NaT,2025-09-29,HEALTH AND HUMAN SERVICES,CENTERS FOR DISEASE CONTROL AND PREVENTION,...,N,N,Firm Fixed Price,Not Reported,Full and Open Competition,Multiple Awards Fair Opportunity,Atlanta,GA,United States,True
649,2025-04-28,MEDICAL EXPERT SERVICES FOR THE VACCINE INJURY...,NaN,Terminate for Convenience (complete or partial),0.0,2021-07-23,NaT,NaT,HEALTH AND HUMAN SERVICES,HEALTH RESOURCES AND SERVICES ADMINISTRATION,...,N,N,Firm Fixed Price,Not Reported,Not Reported,Not Reported,NaN,NaN,Undetermined,True
7978,2025-03-12,SCIENTIFIC OPERATIONS AND ADMINISTRATIVE RESOU...,NaN,Terminate for Convenience (complete or partial),0.0,2021-04-19,NaT,2026-06-21,HEALTH AND HUMAN SERVICES,NATIONAL INSTITUTES OF HEALTH,...,N,N,Firm Fixed Price,Not Reported,Full and Open Competition,Multiple Awards Fair Opportunity,Troy,MI,United States,True
5207,2025-03-31,GSA CONSOLIDATED MULTIPLE AWARD SCHEDULE,GSA CONSOLIDATED MULTIPLE AWARD SCHEDULE,Terminate for Convenience (complete or partial),0.0,NaT,NaT,2026-03-31,HEALTH AND HUMAN SERVICES,FOOD AND DRUG ADMINISTRATION,...,N,N,Labor Hours,Not Reported,Full and Open Competition,Multiple Awards Fair Opportunity,Rockville,MD,United States,True
7887,2025-03-12,SCIENTIFIC OPERATIONS AND ADMINISTRATIVE RESOU...,NaN,Terminate for Convenience (complete or partial),0.0,2021-04-19,NaT,2026-06-21,HEALTH AND HUMAN SERVICES,NATIONAL INSTITUTES OF HEALTH,...,N,N,Firm Fixed Price,Not Reported,Full and Open Competition,Multiple Awards Fair Opportunity,Troy,MI,United States,True
2229,2025-04-17,PROFESSIONAL SCIENTIFIC AND TECHNICAL SUPPORT ...,PROFESSIONAL SCIENTIFIC AND TECHNICAL SUPPORT ...,Terminate for Convenience (complete or partial),0.0,2018-11-21,NaT,2025-04-24,HEALTH AND HUMAN SERVICES,NATIONAL INSTITUTES OF HEALTH,...,N,N,Labor Hours,Not Reported,Full and Open Competition,Multiple Awards Fair Opportunity,Bethesda,MD,United States,True
1221,2025-04-24,PROFESSIONAL SCIENTIFIC AND TECHNICAL SUPPORT ...,PROFESSIONAL SCIENTIFIC AND TECHNICAL SUPPORT ...,Terminate for Convenience (complete or partial),0.0,2018-11-21,NaT,2026-07-30,HEALTH AND HUMAN SERVICES,NATIONAL INSTITUTES OF HEALTH,...,N,N,Labor Hours,Not Reported,Full and Open Competition,Multiple Awards Fair Opportunity,Bethesda,MD,United States,True
400,2025-04-29,METAPHYSICS SOFTWARE,NaN,Terminate for Convenience (complete or partial),0.0,2023-02-27,2025-04-22,2025-04-22,HEALTH AND HUMAN SERVICES,CENTERS FOR DISEASE CONTROL AND PREVENTION,...,N,N,Firm Fixed Price,No Set Aside Used,Not Competed under SAP,Simplified Acquisition,Burlington,MA,United States,True

In [87]:
df_EOI['Action Amt ($K)'].sum()

-16321.060000000001

In [91]:
## Value of contracts terminated with SDBs due to EOI

df_EOI.groupby('Self Certified Small Disadvantaged Business')['Action Amt ($K)'].sum()

/var/folders/q4/gw0xzyt51vn2p6xn25t2vw1m0000gn/T/ipykernel_79329/2876978351.py:1: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  df_EOI.groupby('Self Certified Small Disadvantaged Business')['Action Amt ($K)'].sum()

Self Certified Small Disadvantaged Business
N   -9935.35
Y   -6385.71
Name: Action Amt ($K), dtype: float64

In [101]:
## the ratio of EOI canceled contracts that were with SDBs by value 

EOI_SDB_value_ratio = 6385.71/16321*100
print(round(EOI_SDB_value_ratio,2))

39.13

In [117]:
## states most impacted by EOI terminations by value 

df_EOI.groupby('Place of Performance State')['Action Amt ($K)'].sum().nsmallest(20)

Place of Performance State
MD   -10002.40
GA    -2426.08
VA    -1376.83
DC    -1010.14
CA     -443.18
WA     -282.48
FL     -197.07
OH     -142.63
CO     -140.51
AK      -91.06
NC      -64.39
TX      -48.98
IL      -43.52
WV      -29.17
CT      -11.63
PA       -7.15
MO       -3.84
AL        0.00
AZ        0.00
HI        0.00
Name: Action Amt ($K), dtype: float64

In [5]:
## Breakdown of reasons given for terminating the contract

df1['Reason For Mod'].value_counts().to_frame()

                                                 count
Reason For Mod
Terminate for Convenience (complete or partial)  15086
Legal Contract Cancellation                       1173
Terminate for Cause                                 81
Terminate for Default (complete or partial)         45

In [6]:
df1['Reason For Mod'].value_counts(normalize = True)

Reason For Mod
Terminate for Convenience (complete or partial)    0.920720
Legal Contract Cancellation                        0.071590
Terminate for Cause                                0.004944
Terminate for Default (complete or partial)        0.002746
Name: proportion, dtype: float64

In [7]:
## Distill dataset to only include "Termination for convenience"

filtered_df = df1[df1['Reason For Mod'] == 'Terminate for Convenience (complete or partial)']

# Sample check

filtered_df.sample(5)

,Date Signed / Action Date,Contract Name,Contract Vehicle,Reason For Mod,Action Amt ($K),Contract Award Date,Contract Ultimate Expiration Date,Ultimate Completion Date of Transaction,Contracting Department,Contracting Agency,...,EDWOSB JV,Alaska Native Corporation Owned,AbilityOne,Contract Type,Set-Aside,Extent Competed,Solicitation Procedure,Place of Performance City,Place of Performance State,Place of Performance Country
9099,2025-03-06,DIRECT LEASE IN SUPPORT OF DR4724-HI,NaN,Terminate for Convenience (complete or partial),-102.96,2023-10-17,NaT,2025-01-30,HOMELAND SECURITY,FEDERAL EMERGENCY MANAGEMENT AGENCY,...,N,N,N,Firm Fixed Price,No Set Aside Used,Competed under SAP,Simplified Acquisition,Lahaina,HI,United States
8162,2025-03-11,GSA CONSOLIDATED MULTIPLE AWARD SCHEDULE,GSA CONSOLIDATED MULTIPLE AWARD SCHEDULE,Terminate for Convenience (complete or partial),-1.82,NaT,NaT,2025-03-11,GENERAL SERVICES ADMINISTRATION,FEDERAL ACQUISITION SERVICE,...,N,N,Y,Fixed Price with Economic Price Adjustment,Not Reported,Full and Open Competition,Multiple Awards Fair Opportunity,Durham,NC,United States
6582,2025-03-20,"SOCKET, SOCKET WRENCH: SOCKET WRENCH (8-POINT)...",NaN,Terminate for Convenience (complete or partial),-0.07,2024-12-05,2025-03-20,2025-03-20,GENERAL SERVICES ADMINISTRATION,FEDERAL ACQUISITION SERVICE,...,N,N,N,Firm Fixed Price,No Set Aside Used,Not Competed under SAP,Simplified Acquisition,Troy,MI,United States
3214,2025-04-11,GSA CONSOLIDATED MULTIPLE AWARD SCHEDULE,GSA CONSOLIDATED MULTIPLE AWARD SCHEDULE,Terminate for Convenience (complete or partial),-0.08,NaT,NaT,2025-04-11,GENERAL SERVICES ADMINISTRATION,FEDERAL ACQUISITION SERVICE,...,N,N,N,Fixed Price with Economic Price Adjustment,Not Reported,Full and Open Competition,Multiple Awards Fair Opportunity,Lake Forest,IL,United States
8141,2025-03-11,YOUTH ART AND COMMUNITY PROJECT COMPETITIONS. ...,NaN,Terminate for Convenience (complete or partial),0.00,2024-09-19,2025-02-21,2025-02-21,HEALTH AND HUMAN SERVICES,NATIONAL INSTITUTES OF HEALTH,...,N,Y,N,Firm Fixed Price,8(a) Sole Source,Not Available for Competition,Single Source Solicited,Wasilla,AK,United States

In [8]:
## Calculate the proportion of SDBs that had contracts terminated for convenience

filtered_df.groupby('Self Certified Small Disadvantaged Business').count()

/var/folders/q4/gw0xzyt51vn2p6xn25t2vw1m0000gn/T/ipykernel_79329/2460708900.py:3: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  filtered_df.groupby('Self Certified Small Disadvantaged Business').count()

,Date Signed / Action Date,Contract Name,Contract Vehicle,Reason For Mod,Action Amt ($K),Contract Award Date,Contract Ultimate Expiration Date,Ultimate Completion Date of Transaction,Contracting Department,Contracting Agency,...,EDWOSB JV,Alaska Native Corporation Owned,AbilityOne,Contract Type,Set-Aside,Extent Competed,Solicitation Procedure,Place of Performance City,Place of Performance State,Place of Performance Country
Self Certified Small Disadvantaged Business,,,,,,,,,,,,,,,,,,,,,
N,12287,12287,5380,12287,12287,8547,4096,11950,12287,11773,...,12287,12287,12287,12287,12287,12287,12287,11536,11536,12287
Y,2799,2799,859,2799,2799,2544,1166,2643,2799,2594,...,2799,2799,2799,2799,2799,2799,2799,2596,2596,2799

In [9]:
ratio_SDB = 2799/(2799+12287)*100
round(ratio_SDB,2)

18.55

In [10]:
## Calculate the total value of SDB canceled contracts

filtered_df.groupby('Self Certified Small Disadvantaged Business')['Action Amt ($K)'].sum().to_frame()

/var/folders/q4/gw0xzyt51vn2p6xn25t2vw1m0000gn/T/ipykernel_79329/601764110.py:3: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  filtered_df.groupby('Self Certified Small Disadvantaged Business')['Action Amt ($K)'].sum().to_frame()

                                             Action Amt ($K)
Self Certified Small Disadvantaged Business
N                                                 -531221.72
Y                                                 -115672.36

In [11]:
total_value = filtered_df['Action Amt ($K)'].sum()
total_value

-646894.0800000001

In [12]:
## Calculate the percentage of SDB canceled contract value as percentage of overall canceled contract value for all businesses

self_certified_value = 130301.97/total_value*100
round((self_certified_value)*-1,2)

20.14

In [13]:
## Calculate the percentage of SDB canceled contract numbers as percentage of overall canceled contracts for all businesses 

self_certified_count = 2799/(2799+12287)*100
round(self_certified_count,2)

18.55

In [14]:
## Narrow down the dataset to just self certified small disadvantaged businesses

SDB_df = filtered_df[df['Self Certified Small Disadvantaged Business'] == 'Y']
SDB_df['Self Certified Small Disadvantaged Business'].sample(10)

/var/folders/q4/gw0xzyt51vn2p6xn25t2vw1m0000gn/T/ipykernel_79329/2665393992.py:3: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  SDB_df = filtered_df[df['Self Certified Small Disadvantaged Business'] == 'Y']

13097    Y
13491    Y
9863     Y
8091     Y
8680     Y
1751     Y
12086    Y
8584     Y
3314     Y
12504    Y
Name: Self Certified Small Disadvantaged Business, dtype: category
Categories (2, object): ['N', 'Y']

In [15]:
## List 20 SDB vendors who had most contracts canceled 

SDB_df.groupby(['Vendor'])['Reason For Mod'].count().nlargest(20)

Vendor
F & M MICRO PRODUCTS INC                                      137
MANAGEMENT & ENGINEERING TECHNOLOGIES INTERNATIONAL (METI)     83
VMS AIRCRAFT COMPANY, INC                                      67
MBA OFFICE SUPPLY INC.                                         55
TYNES PROPERTY MANAGEMENT LLC                                  49
DOMESTIC AWARDEES (UNDISCLOSED)                                39
COMPLETE PACKAGING, SHIPPING &                                 38
KPAUL PROPERTIES, LLC                                          36
SYNERGY AMERICA INCORPORATED                                   35
NOREX GROUP, LLC                                               33
AXLE INFORMATICS, LLC                                          28
CHEROKEE NATION BUSINESSES, LLC                                26
ASRT, INC                                                      18
ROSE LI & ASSOCIATES, INC.                                     18
TANAQ SUPPORT SERVICES, LLC                                    17
GOLDBELT, INCORPORATED                                         16
STAG ENTERPRISE INC                                            16
NEW TECH SOLUTIONS, INC (FREMONT, CA)                          15
WINDSOR GROUP                                                  15
STAR POLY BAG, INC.                                            14
Name: Reason For Mod, dtype: int64

In [16]:
## List 20 SDB vendors who had the most value of contracts canceled

SDB_df.groupby(['Vendor'])['Action Amt ($K)'].sum().nlargest(20)

Vendor
HERITAGE INTERIORS, LLC             1353.28
ITS AGILE, LLC                      1233.48
AT-IMPACT LLC                       1117.40
MARVEL CONSULTING LLC                194.50
KAUFFMAN & ASSOCIATES, INC.          108.64
ASCELLA TECHNOLOGIES, INC.            65.12
BLUEPRINT CREATIVE GROUP, LLC         42.33
DYNAMIC INTEGRATED SERVICES, LLC      11.67
11TH HOUR SEARCH                       0.00
2BFOCUSED INC.                         0.00
2M RESEARCH SERVICES, LLC              0.00
2NDWAVE LLC                            0.00
3KPC, INC.                             0.00
4ES CORPORATION                        0.00
A KING DAILEY LLC                      0.00
A P VENTURES, LLC                      0.00
A-1 ANHERMA, LLC                       0.00
A-TEAM SOLUTIONS, LLC                  0.00
A1FEDIMPACT, LLC                       0.00
AALIS MANAGEMENT CONSULTING LLC        0.00
Name: Action Amt ($K), dtype: float64

In [17]:
## Calculate the geographic spread of contract terminations for convenience by count

filtered_df.groupby(['Place of Performance State'])['Action Amt ($K)'].count().nlargest(10)

Place of Performance State
DC    1801
VA    1272
IL    1255
GA    1123
MD    1122
NY    1113
MI     827
MA     675
CA     674
OH     496
Name: Action Amt ($K), dtype: int64

In [18]:
## Calculate the geographic spread of contract terminations for convenience by value

filtered_df.groupby(['Place of Performance State'])['Action Amt ($K)'].sum().nsmallest(10)

Place of Performance State
TX   -113204.36
VA    -87579.18
DC    -87508.71
FL    -61646.05
MD    -37054.61
MI    -36349.82
CA    -30504.57
GA    -23777.52
UT    -23705.93
AZ    -13328.56
Name: Action Amt ($K), dtype: float64

In [19]:
## investigate industry sectors most impacted within SDBs

SDB_df.groupby(['NAICS-Description'])['Action Amt ($K)'].count().nlargest(20).to_frame()

                                                    Action Amt ($K)
NAICS-Description
541611 - Administrative Management and General ...              646
339940 - Office Supplies (except Paper) Manufac...              164
541990 - All Other Professional, Scientific and...              157
541519 - Other Computer Related Services                        144
334111 - Electronic Computer Manufacturing                      111
541512 - Computer Systems Design Services                       100
541690 - Other Scientific and Technical Consult...               87
541511 - Custom Computer Programming Services                    84
541715 - Research and Development in the Physic...               82
236220 - Commercial and Institutional Building ...               62
561110 - Office Administrative Services                          59
611430 - Professional and Management Developmen...               58
314999 - All Other Miscellaneous Textile Produc...               49
322223 - Plastics, Foil, and Coated Paper Bag M...               38
332510 - Hardware Manufacturing                                  38
541612 - Human Resources Consulting Services                     37
812990 - All Other Personal Services                             37
541620 - Environmental Consulting Services                       34
541613 - Marketing Consulting Services                           32
541330 - Engineering Services                                    29

In [20]:
## DEI as part of the contract 

print(filtered_df['Contract Requirement Description'])

0        EOI::IMPLEMENTING THE PRESIDENTS DEPARTMENT OF...
1        EOI:: IMPLEMENTING THE PRESIDENTS DEPARTMENT O...
2        EOI::IMPLEMENTING THE PRESIDENT'S DOGE COST EF...
3        EOI::IMPLEMENTING THE PRESIDENT'S DOGE COST EF...
4          TERMINATION FOR CONVENIENCE; SITE CORE LICENSES
                               ...
16380    JACK, HYDRAULIC, HAND: IAW U. S. ARMY TANK AUT...
16381    FOLDER, FILE: ITEM NAME FOLDER, FILE OVERALL V...
16382                                         SHIPPING BOX
16383    BOX, SHIPPING: ITEM NAME BOX, SHIPPING I.A.W. ...
16384                                           CHAIR,EASY
Name: Contract Requirement Description, Length: 15086, dtype: string

In [21]:
## import subcontractor data 

dfsub = pd.read_excel("data/DeltekDataSubMay2025.xlsx")
dfsub.info()

/opt/anaconda3/lib/python3.12/site-packages/openpyxl/worksheet/_read_only.py:85: UserWarning: Cell D1749 is marked as a date but the serial value 4700256154 is outside the limits for dates. The cell will be treated as an error.
  for idx, row in parser.parse():
/opt/anaconda3/lib/python3.12/site-packages/openpyxl/worksheet/_read_only.py:85: UserWarning: Cell D1750 is marked as a date but the serial value 4700323399 is outside the limits for dates. The cell will be treated as an error.
  for idx, row in parser.parse():
/opt/anaconda3/lib/python3.12/site-packages/openpyxl/worksheet/_read_only.py:85: UserWarning: Cell D1751 is marked as a date but the serial value 4700324086 is outside the limits for dates. The cell will be treated as an error.
  for idx, row in parser.parse():
/opt/anaconda3/lib/python3.12/site-packages/openpyxl/worksheet/_read_only.py:85: UserWarning: Cell D2142 is marked as a date but the serial value 4700469719 is outside the limits for dates. The cell will be treated as an error.
  for idx, row in parser.parse():
/opt/anaconda3/lib/python3.12/site-packages/openpyxl/worksheet/_read_only.py:85: UserWarning: Cell D2143 is marked as a date but the serial value 4700469202 is outside the limits for dates. The cell will be treated as an error.
  for idx, row in parser.parse():
/opt/anaconda3/lib/python3.12/site-packages/openpyxl/worksheet/_read_only.py:85: UserWarning: Cell D2144 is marked as a date but the serial value 4700469189 is outside the limits for dates. The cell will be treated as an error.
  for idx, row in parser.parse():
/opt/anaconda3/lib/python3.12/site-packages/openpyxl/worksheet/_read_only.py:85: UserWarning: Cell D2279 is marked as a date but the serial value 2300000399 is outside the limits for dates. The cell will be treated as an error.
  for idx, row in parser.parse():
/opt/anaconda3/lib/python3.12/site-packages/openpyxl/worksheet/_read_only.py:85: UserWarning: Cell D2280 is marked as a date but the serial value 5300011063 is outside the limits for dates. The cell will be treated as an error.
  for idx, row in parser.parse():
/opt/anaconda3/lib/python3.12/site-packages/openpyxl/worksheet/_read_only.py:85: UserWarning: Cell D2281 is marked as a date but the serial value 2300000398 is outside the limits for dates. The cell will be treated as an error.
  for idx, row in parser.parse():

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3563 entries, 0 to 3562
Data columns (total 21 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   SubAward Action Date         3563 non-null   datetime64[ns]
 1   SubAward Action Fiscal Year  3563 non-null   int64
 2   SubAward Amount ($K)         3563 non-null   float64
 3   SubAward #                   3554 non-null   object
 4   SubAward Description         3562 non-null   object
 5   Subcontractor                3563 non-null   object
 6   Sub Socio Status             2486 non-null   object
 7   PoP Country                  3563 non-null   object
 8   PoP State                    3041 non-null   object
 9   PoP City                     3380 non-null   object
 10  PoP Zip                      3112 non-null   object
 11  NAICS                        3563 non-null   int64
 12  NAICS Description            3563 non-null   object
 13  Prime Contract #             3563 non-null   object
 14  Prime Task Order #           3563 non-null   object
 15  Prime Contractor             3563 non-null   object
 16  Prime Socio Status           2212 non-null   object
 17  Funding Department           3563 non-null   object
 18  Funding Agency               3386 non-null   object
 19  Funding Office               2398 non-null   object
 20  Funding Division             407 non-null    object
dtypes: datetime64[ns](1), float64(1), int64(2), object(17)
memory usage: 584.7+ KB

In [22]:
## clean the dataset and remove columns

dfsub1 = dfsub.drop(dfsub.columns[[1,3,7,10,13,14,19,20]], axis=1)
dfsub1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3563 entries, 0 to 3562
Data columns (total 13 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   SubAward Action Date  3563 non-null   datetime64[ns]
 1   SubAward Amount ($K)  3563 non-null   float64
 2   SubAward Description  3562 non-null   object
 3   Subcontractor         3563 non-null   object
 4   Sub Socio Status      2486 non-null   object
 5   PoP State             3041 non-null   object
 6   PoP City              3380 non-null   object
 7   NAICS                 3563 non-null   int64
 8   NAICS Description     3563 non-null   object
 9   Prime Contractor      3563 non-null   object
 10  Prime Socio Status    2212 non-null   object
 11  Funding Department    3563 non-null   object
 12  Funding Agency        3386 non-null   object
dtypes: datetime64[ns](1), float64(1), int64(1), object(10)
memory usage: 362.0+ KB

In [23]:
dfsub1.head()

,SubAward Action Date,SubAward Amount ($K),SubAward Description,Subcontractor,Sub Socio Status,PoP State,PoP City,NAICS,NAICS Description,Prime Contractor,Prime Socio Status,Funding Department,Funding Agency
0,2021-05-25,100.86,SUBCONTRACTOR WILL BE PERFORMING THE SPRAY FOA...,"DIVISION 7, INC.",Women-Owned,CO,BOULDER,236220,Commercial and Institutional Building Construc...,WHITING-TURNER CONTRACTING COMPANY,NaN,COMMERCE,NATIONAL INSTITUTE OF STANDARDS AND TECHNOLOGY
1,2021-06-09,1557.00,SUBCONTRACTOR WILL FURNISH AND INSTALL TELECOM...,STURGEON ELECTRIC CO INC,NaN,CO,BOULDER,236220,Commercial and Institutional Building Construc...,WHITING-TURNER CONTRACTING COMPANY,NaN,COMMERCE,NATIONAL INSTITUTE OF STANDARDS AND TECHNOLOGY
2,2021-03-03,1224.72,SUBCONTRACTOR IS RESPONSIBLE FOR FURNISH AND ...,"BAKER CONCRETE CONSTRUCTION, INC",NaN,CO,BOULDER,236220,Commercial and Institutional Building Construc...,WHITING-TURNER CONTRACTING COMPANY,NaN,COMMERCE,NATIONAL INSTITUTE OF STANDARDS AND TECHNOLOGY
3,2021-03-12,1111.99,SUBCONTRACTOR IS RESPONSIBLE FOR FURNISH AND I...,"SANTA FE GLASS, INC.",Small Business (in one or more NAICS)|Small Bu...,CO,BOULDER,236220,Commercial and Institutional Building Construc...,WHITING-TURNER CONTRACTING COMPANY,NaN,COMMERCE,NATIONAL INSTITUTE OF STANDARDS AND TECHNOLOGY
4,2021-03-24,50.00,"SUBCONTRACTOR SHALL FURNISH, INSTALL AND REMOV...","AMERICAN FENCE AND SECURITY COMPANY, INC.",Small Business (in one or more NAICS),CO,BOULDER,236220,Commercial and Institutional Building Construc...,WHITING-TURNER CONTRACTING COMPANY,NaN,COMMERCE,NATIONAL INSTITUTE OF STANDARDS AND TECHNOLOGY

In [24]:
dfsub1['Sub Socio Status'].unique()

array(['Women-Owned', nan,
       'Small Business (in one or more NAICS)|Small Business Joint Venture|Small Disadvantaged Business',
       'Small Business (in one or more NAICS)',
       'Limited Liability Company|Small Business (in one or more NAICS)',
       'DOT Certified DBE|SBA-Certified Women-Owned Small Business|Small Business (in one or more NAICS)|Women-Owned|Women-Owned Small Business',
       'SBA-Certified Veteran-Owned Small Business|Small Business (in one or more NAICS)|Small Disadvantaged Business|Veteran-Owned',
       'Limited Liability Company',
       'DOT Certified DBE|Hispanic American-Owned|Limited Liability Company|Manufacturer of Goods|Minority-Owned|Small Business (in one or more NAICS)|Small Disadvantaged Business',
       'Alaskan Native Corporation-Owned|Indian Economic Enterprise|Indian Small Business Economic Enterprise|Limited Liability Company|Minority-Owned|Native American-Owned|SBA-Certified 8(a)|Small Business (in one or more NAICS)|Small Disadvantaged Business|Tribally-Owned',
       'Manufacturer of Goods',
       'Manufacturer of Goods|Small Business (in one or more NAICS)',
       'Manufacturer of Goods|Small Business (in one or more NAICS)|Small Disadvantaged Business|Women-Owned',
       'Limited Liability Company|Manufacturer of Goods|Small Business (in one or more NAICS)',
       'Limited Liability Company|Minority-Owned|Small Business (in one or more NAICS)|Small Disadvantaged Business|Subcontinent Asian American-Owned',
       'Limited Liability Company|Manufacturer of Goods',
       'Limited Liability Company|Small Business (in one or more NAICS)|Women-Owned|Women-Owned Small Business',
       'Foreign-Owned',
       'Hispanic American-Owned|Manufacturer of Goods|Minority-Owned|Small Business (in one or more NAICS)|Small Disadvantaged Business|Women-Owned|Women-Owned Small Business',
       'Limited Liability Company|Manufacturer of Goods|Small Business (in one or more NAICS)|Small Disadvantaged Business',
       'Manufacturer of Goods|Small Business (in one or more NAICS)|Small Disadvantaged Business|Women-Owned|Women-Owned Small Business',
       'Manufacturer of Goods|Small Business (in one or more NAICS)|Women-Owned|Women-Owned Small Business',
       'Foreign-Owned|Manufacturer of Goods',
       'Small Business (in one or more NAICS)|Veteran-Owned',
       'Small Business (in one or more NAICS)|Small Disadvantaged Business|Women-Owned|Women-Owned Small Business',
       'Hispanic American-Owned|Manufacturer of Goods|SBA-Certified HUBZone|Small Business (in one or more NAICS)|Women-Owned|Women-Owned Small Business',
       'Manufacturer of Goods|Small Business (in one or more NAICS)|Women-Owned',
       'Limited Liability Company|Small Business Joint Venture',
       'SBA-Certified 8(a)|SBA-Certified Women-Owned Small Business|Small Business (in one or more NAICS)|Women-Owned|Women-Owned Small Business',
       'Small Business (in one or more NAICS)|Women-Owned|Women-Owned Small Business',
       'Asian-Pacific American-Owned|Minority-Owned|Small Business (in one or more NAICS)',
       'Individual or concern, other than one of the proceeding|Manufacturer of Goods|Minority-Owned|Small Business (in one or more NAICS)|Small Disadvantaged Business|Women-Owned|Women-Owned Small Business',
       'Economically Disadvantaged Women-Owned Small Business|Manufacturer of Goods|Small Business (in one or more NAICS)|Small Disadvantaged Business|Women-Owned|Women-Owned Small Business',
       'Hispanic American-Owned|Minority-Owned|Small Business (in one or more NAICS)|Women-Owned|Women-Owned Small Business',
       'Limited Liability Company|Manufacturer of Goods|Small Business (in one or more NAICS)|Veteran-Owned',
       'Manufacturer of Goods|SBA-Certified HUBZone|Small Business (in one or more NAICS)',
       'Asian-Pacific American-Owned|Limited Liability Company|Manufacturer of Goods|Minority-Owned|Small Business (in one or more NAICS)',
       'Limited Liability Company|Small Business (in one or more NAICS)|Small Disadvantaged Business',
       'Hispanic American-Owned|Manufacturer of Goods|Minority-Owned',
       'Minority-Owned|Small Business (in one or more NAICS)|Small Disadvantaged Business|Subcontinent Asian American-Owned',
       'DOT Certified DBE|Hispanic American-Owned|Small Business (in one or more NAICS)|Veteran-Owned',
       'Manufacturer of Goods|Small Business (in one or more NAICS)|Veteran-Owned',
       'Minority-Owned|Small Business (in one or more NAICS)|Subcontinent Asian American-Owned',
       'Economically Disadvantaged Women-Owned Small Business|Manufacturer of Goods|Small Business (in one or more NAICS)|Women-Owned',
       'DOT Certified DBE|Hispanic American-Owned|Minority-Owned|Small Business (in one or more NAICS)|Small Disadvantaged Business',
       'Non-Profit|Women-Owned', 'Non-Profit',
       'Individual or concern, other than one of the proceeding|Limited Liability Company|Minority-Owned|Small Business (in one or more NAICS)|Small Disadvantaged Business',
       'Hispanic American-Owned|Minority-Owned|Non-Profit',
       'Other Not for Profit Organization',
       'Small Business (in one or more NAICS)|Small Disadvantaged Business',
       'Community Development Corporation-Owned|Individual or concern, other than one of the proceeding|Minority-Owned|Non-Profit',
       'U.S. State Government',
       'Foundation|Hispanic American-Owned|Minority-Owned|Non-Profit',
       'Community Development Corporation|Non-Profit',
       'Individual or concern, other than one of the proceeding|Minority-Owned|Non-Profit',
       'Economically Disadvantaged Women-Owned Small Business|Hispanic American-Owned|Minority-Owned|Small Business (in one or more NAICS)|Small Disadvantaged Business|Women-Owned|Women-Owned Small Business',
       'Hispanic American-Owned|Minority-Owned|SBA-Certified HUBZone|SBA-Certified Service-Disabled Veteran-Owned Small Business|Service-Disabled Veteran-Owned Small Business|Small Business (in one or more NAICS)|Small Disadvantaged Business|Veteran-Owned',
       'SBA-Certified HUBZone|Small Business (in one or more NAICS)',
       'Black American-Owned|DOT Certified DBE|Economically Disadvantaged Women-Owned Small Business JV|Limited Liability Company|Minority-Owned|Small Business (in one or more NAICS)|Small Disadvantaged Business|Women-Owned Small Business JV',
       'DOT Certified DBE|Hispanic American-Owned|Limited Liability Company|Minority-Owned|Small Business (in one or more NAICS)|Small Disadvantaged Business',
       'Limited Liability Company|Minority-Owned|Small Business (in one or more NAICS)|Subcontinent Asian American-Owned',
       'Hispanic American-Owned|Limited Liability Company|Minority-Owned',
       'Economically Disadvantaged Women-Owned Small Business|Hispanic American-Owned|Minority-Owned|SBA-Certified Economically Disadvantaged Women-Owned Small Business|SBA-Certified HUBZone|SBA-Certified Women-Owned Small Business|Small Business (in one or more NAICS)|Small Disadvantaged Business|Women-Owned|Women-Owned Small Business',
       'SBA-Certified Service-Disabled Veteran-Owned Small Business|Service-Disabled Veteran-Owned Small Business|Small Business (in one or more NAICS)|Veteran-Owned',
       'Black American-Owned|DOT Certified DBE|Minority-Owned|Small Business (in one or more NAICS)|Small Disadvantaged Business',
       'Asian-Pacific American-Owned|Minority-Owned|Small Business (in one or more NAICS)|Small Disadvantaged Business|Women-Owned',
       'Minority-Owned|Subcontinent Asian American-Owned|Women-Owned',
       'SBA-Certified Women-Owned Small Business|Small Business (in one or more NAICS)|Women-Owned|Women-Owned Small Business',
       'Indian Economic Enterprise|Limited Liability Company|Minority-Owned|Native American-Owned|SBA-Certified 8(a)|SBA-Certified HUBZone|Small Business (in one or more NAICS)|Small Disadvantaged Business|Tribally-Owned',
       'Minority-Owned|Small Business (in one or more NAICS)|Subcontinent Asian American-Owned|Women-Owned',
       'Limited Liability Company|Small Business (in one or more NAICS)|Small Business Joint Venture',
       'Limited Liability Company|Small Business (in one or more NAICS)|Small Disadvantaged Business|Women-Owned|Women-Owned Small Business',
       'Asian-Pacific American-Owned|Manufacturer of Goods|Minority-Owned|Small Business (in one or more NAICS)|Small Disadvantaged Business',
       'Educational Institution|Non-Profit|Private University or College',
       'Educational Institution|State-Controlled Institution of Higher Learning|U.S. State Government',
       'Small Business (in one or more NAICS)|Women-Owned',
       'Educational Institution|Foreign-Owned|Non-Profit|Private University or College',
       'Alaskan Native Corporation-Owned|American Indian-Owned|Indian Tribe (Federally Recognized)|Native Hawaiian Organization-Owned|Non-Profit|Tribally-Owned',
       'Foundation|Non-Profit',
       'Minority-Owned|Small Business (in one or more NAICS)|Small Disadvantaged Business|Women-Owned',
       'Alaskan Native Corporation-Owned|Limited Liability Company|Minority-Owned|Native American-Owned|Small Business (in one or more NAICS)|Small Disadvantaged Business',
       'Limited Liability Company|SBA-Certified Women-Owned Small Business|Small Business (in one or more NAICS)|Women-Owned|Women-Owned Small Business',
       'DOT Certified DBE|Minority-Owned|Small Business (in one or more NAICS)|Small Disadvantaged Business|Subcontinent Asian American-Owned',
       'Hispanic American-Owned|Minority-Owned|Small Business (in one or more NAICS)|Small Disadvantaged Business',
       'Minority-Owned|SBA-Certified 8(a)|Small Business (in one or more NAICS)|Small Disadvantaged Business|Subcontinent Asian American-Owned|Women-Owned|Women-Owned Small Business',
       'DOT Certified DBE|Limited Liability Company|SBA-Certified 8(a)|Small Business (in one or more NAICS)|Small Disadvantaged Business|Subcontinent Asian American-Owned',
       'Asian-Pacific American-Owned|Minority-Owned|SBA-Certified Economically Disadvantaged Women-Owned Small Business|SBA-Certified Women-Owned Small Business|Small Business (in one or more NAICS)|Women-Owned|Women-Owned Small Business',
       'Asian-Pacific American-Owned|Economically Disadvantaged Women-Owned Small Business|Minority-Owned|SBA-Certified 8(a)|SBA-Certified Economically Disadvantaged Women-Owned Small Business|SBA-Certified Women-Owned Small Business|Small Business (in one or more NAICS)|Small Disadvantaged Business|Women-Owned|Women-Owned Small Business',
       'Limited Liability Company|SBA-Certified Service-Disabled Veteran-Owned Small Business|SBA-Certified Women-Owned Small Business|Service-Disabled Veteran-Owned Small Business|Small Business (in one or more NAICS)|Veteran-Owned|Women-Owned|Women-Owned Small Business',
       'HUBZone Joint Venture|Limited Liability Company',
       'DOT Certified DBE|Hispanic American-Owned|Minority-Owned|SBA-Certified 8(a)|Small Business (in one or more NAICS)|Small Disadvantaged Business',
       'Limited Liability Company|SBA-Certified HUBZone|SBA-Certified Women-Owned Small Business|Small Business (in one or more NAICS)',
       'DOT Certified DBE|SBA-Certified 8(a)|SBA-Certified Economically Disadvantaged Women-Owned Small Business|SBA-Certified Women-Owned Small Business|Small Business (in one or more NAICS)|Small Disadvantaged Business|Subcontinent Asian American-Owned|Women-Owned|Women-Owned Small Business',
       'Hispanic American-Owned|Limited Liability Company|Minority-Owned|SBA-Certified 8(a)',
       'Economically Disadvantaged Women-Owned Small Business|SBA-Certified Economically Disadvantaged Women-Owned Small Business|SBA-Certified HUBZone|SBA-Certified Women-Owned Small Business|Small Business (in one or more NAICS)|Women-Owned|Women-Owned Small Business',
       'Economically Disadvantaged Women-Owned Small Business|Limited Liability Company|Minority-Owned|SBA-Certified Economically Disadvantaged Women-Owned Small Business|SBA-Certified Women-Owned Small Business|Small Business (in one or more NAICS)|Small Disadvantaged Business|Subcontinent Asian American-Owned|Women-Owned|Women-Owned Small Business',
       'Small Business (in one or more NAICS)|Small Disadvantaged Business|Subcontinent Asian American-Owned',
       'Limited Liability Company|Minority-Owned|Subcontinent Asian American-Owned|Women-Owned',
       'Limited Liability Company|Minority-Owned|Small Business (in one or more NAICS)|Subcontinent Asian American-Owned|Women-Owned|Women-Owned Small Business',
       'Asian-Pacific American-Owned|Minority-Owned|Small Business (in one or more NAICS)|Women-Owned|Women-Owned Small Business',
       'Economically Disadvantaged Women-Owned Small Business|Minority-Owned|Small Business (in one or more NAICS)|Small Disadvantaged Business|Subcontinent Asian American-Owned|Women-Owned|Women-Owned Small Business',
       'DOT Certified DBE|Limited Liability Company|SBA-Certified Economically Disadvantaged Women-Owned Small Business|SBA-Certified Women-Owned Small Business|Small Business (in one or more NAICS)|Small Disadvantaged Business|Subcontinent Asian American-Owned|Women-Owned|Women-Owned Small Business',
       'Black American-Owned|Limited Liability Company|Minority-Owned|SBA-Certified 8(a)|Small Business (in one or more NAICS)|Small Disadvantaged Business',
       'Black American-Owned|Limited Liability Company|Minority-Owned|Small Business (in one or more NAICS)|Small Disadvantaged Business',
       'Limited Liability Company|Women-Owned',
       'DOT Certified DBE|Economically Disadvantaged Women-Owned Small Business|Minority-Owned|SBA-Certified 8(a)|SBA-Certified Economically Disadvantaged Women-Owned Small Business|SBA-Certified Women-Owned Small Business|Small Business (in one or more NAICS)|Small Disadvantaged Business|Subcontinent Asian American-Owned|Women-Owned|Women-Owned Small Business',
       'Economically Disadvantaged Women-Owned Small Business|Limited Liability Company|Minority-Owned|SBA-Certified 8(a)|Small Business (in one or more NAICS)|Small Disadvantaged Business|Subcontinent Asian American-Owned|Women-Owned|Women-Owned Small Business',
       'Asian-Pacific American-Owned|Minority-Owned|Small Business (in one or more NAICS)|Small Disadvantaged Business',
       'American Indian-Owned|Indian Economic Enterprise|Limited Liability Company|Minority-Owned|Native American-Owned|SBA-Certified 8(a)|Small Business (in one or more NAICS)|Small Disadvantaged Business|Tribally-Owned',
       'Black American-Owned|Limited Liability Company|Minority-Owned|Small Business (in one or more NAICS)|Small Disadvantaged Business|Women-Owned|Women-Owned Small Business',
       'Small Business (in one or more NAICS)|Subcontinent Asian American-Owned',
       'Minority-Owned|Small Business (in one or more NAICS)|Subcontinent Asian American-Owned|Women-Owned|Women-Owned Small Business',
       'Black American-Owned|Minority-Owned|Small Business (in one or more NAICS)|Small Disadvantaged Business',
       'Black American-Owned|DOT Certified DBE|Limited Liability Company|SBA-Certified 8(a)|SBA-Certified Service-Disabled Veteran-Owned Small Business|Service-Disabled Veteran-Owned Small Business|Small Business (in one or more NAICS)|Small Disadvantaged Business|Veteran-Owned',
       'SBA-Certified 8(a)|SBA-Certified Economically Disadvantaged Women-Owned Small Business|SBA-Certified Women-Owned Small Business|Small Business (in one or more NAICS)|Small Disadvantaged Business|Subcontinent Asian American-Owned|Women-Owned|Women-Owned Small Business',
       'Limited Liability Company|Small Business (in one or more NAICS)|Veteran-Owned',
       'Economically Disadvantaged Women-Owned Small Business|SBA-Certified Economically Disadvantaged Women-Owned Small Business|Small Business (in one or more NAICS)|Women-Owned|Women-Owned Small Business',
       'Individual or concern, other than one of the proceeding|Minority-Owned|SBA-Certified Women-Owned Small Business|Small Business (in one or more NAICS)|Small Disadvantaged Business|Women-Owned|Women-Owned Small Business',
       'HUBZone Joint Venture|Limited Liability Company|Small Business (in one or more NAICS)',
       'DOT Certified DBE|SBA-Certified HUBZone|Small Business (in one or more NAICS)|Small Disadvantaged Business|Women-Owned|Women-Owned Small Business',
       'DOT Certified DBE|Economically Disadvantaged Women-Owned Small Business|SBA-Certified 8(a)|SBA-Certified Economically Disadvantaged Women-Owned Small Business|SBA-Certified Service-Disabled Veteran-Owned Small Business|SBA-Certified Women-Owned Small Business|Service-Disabled Veteran-Owned Small Business|Small Business (in one or more NAICS)|Veteran-Owned|Women-Owned|Women-Owned Small Business',
       'Limited Liability Company|SBA-Certified Women-Owned Small Business|Small Business (in one or more NAICS)|Women-Owned',
       'Black American-Owned|Economically Disadvantaged Women-Owned Small Business|Limited Liability Company|Minority-Owned|SBA-Certified Service-Disabled Veteran-Owned Small Business|Service-Disabled Veteran-Owned Small Business|Small Business (in one or more NAICS)|Small Disadvantaged Business|Veteran-Owned|Women-Owned|Women-Owned Small Business',
       'Small Business (in one or more NAICS)|Small Disadvantaged Business|Women-Owned',
       'DOT Certified DBE|Minority-Owned|SBA-Certified Women-Owned Small Business|Small Business (in one or more NAICS)|Small Disadvantaged Business|Subcontinent Asian American-Owned|Women-Owned|Women-Owned Small Business',
       'SBA-Certified Women-Owned Small Business|Small Business (in one or more NAICS)|Small Disadvantaged Business|Subcontinent Asian American-Owned|Women-Owned|Women-Owned Small Business',
       'Economically Disadvantaged Women-Owned Small Business|Minority-Owned|SBA-Certified 8(a)|SBA-Certified Economically Disadvantaged Women-Owned Small Business|SBA-Certified HUBZone|SBA-Certified Women-Owned Small Business|Small Business (in one or more NAICS)|Small Disadvantaged Business|Subcontinent Asian American-Owned|Women-Owned|Women-Owned Small Business',
       'Black American-Owned|DOT Certified DBE|Limited Liability Company|Minority-Owned|Small Business (in one or more NAICS)|Small Disadvantaged Business',
       'Economically Disadvantaged Women-Owned Small Business|Minority-Owned|SBA-Certified 8(a)|SBA-Certified Economically Disadvantaged Women-Owned Small Business|SBA-Certified Women-Owned Small Business|Small Business (in one or more NAICS)|Small Disadvantaged Business|Subcontinent Asian American-Owned|Women-Owned|Women-Owned Small Business',
       'Minority-Owned|Subcontinent Asian American-Owned',
       'Asian-Pacific American-Owned|Minority-Owned|Small Business (in one or more NAICS)|Women-Owned',
       'SBA-Certified Economically Disadvantaged Women-Owned Small Business|SBA-Certified HUBZone|SBA-Certified Service-Disabled Veteran-Owned Small Business|SBA-Certified Women-Owned Small Business|Service-Disabled Veteran-Owned Small Business|Small Business (in one or more NAICS)|Small Disadvantaged Business|Veteran-Owned|Women-Owned|Women-Owned Small Business',
       'Limited Liability Company|Small Business (in one or more NAICS)|Small Disadvantaged Business|Veteran-Owned',
       'Small Business (in one or more NAICS)|Small Disadvantaged Business|Subcontinent Asian American-Owned|Women-Owned|Women-Owned Small Business',
       'Alaskan Native Corporation-Owned|Minority-Owned|Native American-Owned',
       'Minority-Owned|SBA-Certified Women-Owned Small Business|Small Business (in one or more NAICS)|Small Disadvantaged Business|Subcontinent Asian American-Owned|Women-Owned|Women-Owned Small Business',

In [25]:
dfsub1[['Sub Socio Status', 'Prime Socio Status']] = dfsub1[['Sub Socio Status', 'Prime Socio Status']].astype("string")
dfsub1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3563 entries, 0 to 3562
Data columns (total 13 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   SubAward Action Date  3563 non-null   datetime64[ns]
 1   SubAward Amount ($K)  3563 non-null   float64
 2   SubAward Description  3562 non-null   object
 3   Subcontractor         3563 non-null   object
 4   Sub Socio Status      2486 non-null   string
 5   PoP State             3041 non-null   object
 6   PoP City              3380 non-null   object
 7   NAICS                 3563 non-null   int64
 8   NAICS Description     3563 non-null   object
 9   Prime Contractor      3563 non-null   object
 10  Prime Socio Status    2212 non-null   string
 11  Funding Department    3563 non-null   object
 12  Funding Agency        3386 non-null   object
dtypes: datetime64[ns](1), float64(1), int64(1), object(8), string(2)
memory usage: 362.0+ KB

In [26]:
dfsub1.loc[dfsub1['Sub Socio Status'].str.contains('Small Disadvantaged Business'), 'Small Disadvantaged Business'] = 'Y'
dfsub1.count(10)

ValueError: No axis named 10 for object type DataFrame

In [ ]:
dfsub1.query("`Prime Socio Status` == 'Small Disadvantaged Business'")